steps:
  # Docker Build Image
  - name: gcr.io/cloud-builders/docker
    id  : BUILD
    args: ['build', '--file=Dockerfile', '-t', '$_SERVICE_IMAGE', '.']

  # Docker Push Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id  : PUSH
    args: ['push', '$_SERVICE_IMAGE']

  # Docker Deploy image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$_SERVICE_PROJECT
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE

images: # Display the image in the build results - Build Artifacts
  - $_SERVICE_IMAGE

substitutions:
  _SERVICE_IMAGE    : europe-west3-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
  _SERVICE_REGION   : europe-west3
  _SERVICE_PROJECT  : hilligan-anime-bot
  _SERVICE_NAME     : anime-bot
  _DOCKER_REGISTRY  : anime-bot
  _DOCKER_IMAGENAME : anime-bot